name: Project_app
description: First flutter project
dependencies:
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
flutter:
   uses-material-design: true